### ISSUE TITLE
itwinai logo

### ISSUE THREAD

**Issue by matbun** [interTwin-eu/itwinai#166]

**Comment by KalliopiTsolaki** [comment]
Contacted Gwen (interTwin comms team) for support, sharing the canva prototypes. Project designer will provide finetuning on the designs.
Canva prototypes:
- [prototype 1] (https://www.canva.com/design/DAGGJLC7lE8/52K7kvzCVBa3kHd_0Btqfw/edit?utm_content=DAGGJLC7lE8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [prototype 2] (https://www.canva.com/design/DAGHRlssyxM/kLXtaxHcNdaWJAfiV9VC0A/edit?utm_content=DAGHRlssyxM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [prototype 3] (https://www.canva.com/design/DAGHWsAzlLg/vw85JllZrtMQ9_sVq8PPFg/edit?utm_content=DAGHWsAzlLg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by KalliopiTsolaki** [comment]
Contacted Gwen on 2/7 and we got informed that the designer is expected to work on the logo next week.

**Comment by KalliopiTsolaki** [comment]
1st project designer logo. Asked for capitalization of words in the text, like "AI on Cloud & HPC for Science".

![Image](https://github.com/user-attachments/assets/de3b0021-011c-463d-8ae7-276870cfbbef)

**Comment by KalliopiTsolaki** [comment]
Logo in different variations:

![Image](https://github.com/user-attachments/assets/6d0d4d38-6fa5-4ed3-ac00-3a029308dc8a)
![Image](https://github.com/user-attachments/assets/52bd25bc-dfd6-4962-a21d-c1a468472ca9)
![Image](https://github.com/user-attachments/assets/4d55ba7c-1930-4759-b549-ae8bfa73398b)
![Image](https://github.com/user-attachments/assets/2b9d6136-daf4-4680-945c-0dc739621dc7)
![Image](https://github.com/user-attachments/assets/bbcd2178-5723-485e-a9be-1563dc77ee3f)
![Image](https://github.com/user-attachments/assets/4a545da7-e4f6-422a-a37c-38691732193b)
![Image](https://github.com/user-attachments/assets/5ce32130-2a2a-4045-8344-bbde436c4526)
![Image](https://github.com/user-attachments/assets/e3e05ada-3dc6-4844-91fa-625c366674c4)

**Comment by matbun** [comment]
@KalliopiTsolaki could you create a new branch and add the logo both to the main README and to the docs page, please?

**Comment by KalliopiTsolaki** [comment]
DONE: coordination is required for the aesthetic details

**Comment by matbun** [comment]
Thanks @KalliopiTsolaki . Could you open a PR please?
