### ISSUE TITLE
DeepSpeed strategy crashing when run on more than one node

### ISSUE THREAD

**Issue by annaelisalappe** [interTwin-eu/itwinai#208]
**Describe the bug**
The DeepSpeed strategy crashes if it is run on more than one node. This is the case in the torch-tutorials 1, 2 and 5. The error message that arises is: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!`.

**To Reproduce**
To reproduce in the MNIST-tutorial:
1. Run the tutorial as described [here](https://itwinai.readthedocs.io/latest/tutorials/distrib-ml/torch_tutorial_1_mnist.html) using the distributed mode (SLURM) with the deepspeed option. 
2. The error is displayed in the file job-deepspeed-itwinai-n.err in the logs_slurm folder. 
All epochs are still finishing, so it seems that only one worker is affected by this error.

**Expected behavior**
The train.py file should run without any error message.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by matbun** [comment]
Is this going to be fixed by #209 ?

**Comment by annaelisalappe** [comment]
Yes 👍🏼On 17 Sep 2024, at 07:58, Matteo Bunino ***@***.***> wrote:﻿
Is this going to be fixed by #209 ?
