### ISSUE TITLE
Integrate CMCC use case

### ISSUE THREAD

**Issue by MrGweep** [interTwin-eu/itwinai#44]
Integrate CMCC use case into prototype.
Code repository can be found [here](https://github.com/CMCC-Foundation/ml-tropical-cyclones-detection).
Data is accessible via google drive [here](https://drive.google.com/drive/folders/1pQPF604FS2AIp3n0a8lCNRZlMVLf3ci1?usp=share_link).

There are multiple tasks to be done:
- check that code is working as provided in the repo
- split use case in preprocessing, training, validation/post-processing part
- integrate by porting to PyTorch or providing TF support

**Comment by matbun** [comment]
Adapt to the new "pipeline" API
